### ISSUE TITLE
How the App re-render whole App when language change?

### ISSUE THREAD

**Issue by Jancat** [appfoundry/react-native-multi-language-sample#5]
I saw the code in the sample project:
**SettingsRedux.js**

    // request the data from an api
    export const changeLanguage = (state, {language}) => state.merge({
      language
    })

What's the `state.merge` method?

And Why the App re-render after calling above method?

**Comment by FDMatthias** [comment]
It comes from [seamless-immutable's merge](https://github.com/rtfeldman/seamless-immutable#merge), which is available since we created our initial state with Immutable() on [this line](https://github.com/appfoundry/react-native-multi-language-sample/blob/06cc9494ad57a8cb198f2bea48221d85b573b968/MultiLangSampleApp/App/Redux/SettingsRedux.js#L15).

The app re-renders because our containers are connected to the language setting from this settings redux, and triggers a reload.
